// Browser-safe entrypoint for @drift-labs/common.
//
// IMPORTANT:
// - Do NOT export node-only modules here (e.g. redis client, winston logger, CLI).
// - This file is used for the browser-minified esbuild bundle.

export * from '../Config';
export * from '../chartConstants';
export * from '../types';
export * from '../EnvironmentConstants';
export * from '../serializableTypes';

export * from '../constants';
export * from '../common-ui-utils';

// Utilities (intentionally excludes `../utils/logger`).
export * from '../utils';
export * from '../utils/SharedInterval';
export * from '../utils/Stopwatch';
export * from '../utils/priority-fees';
export * from '../utils/priorityFees';
export * from '../utils/superstake';
export * from '../utils/fetch';
export * from '../utils/priceImpact';
export * from '../utils/dlob-server/DlobServerWebsocketUtils';
export * from '../utils/pollingSequenceGuard';
export * from '../utils/driftEvents';
export * from '../utils/SlotBasedResultValidator';
export * from '../utils/CircularBuffers';
export * from '../utils/rxjs';
export * from '../utils/NumLib';

// Clients (browser-compatible only; intentionally excludes `redisClient`).
export * from '../clients/candleClient';
export * from '../clients/marketDataFeed';
export * from '../clients/swiftClient';
export * from '../clients/tvFeed';
export * from '../clients/DlobWebsocketClient';
export * from '../clients/dataApiWsClient';

// External program errors
import JupV4Errors from '../constants/autogenerated/jup-v4-error-codes.json';
import JupV6Errors from '../constants/autogenerated/jup-v6-error-codes.json';
import DriftErrors from '../constants/autogenerated/driftErrors.json';

export { DriftErrors, JupV4Errors, JupV6Errors };
