export const GEOBLOCK_LIST = [
	// < Not able to do these at the moment >
	// {name: "Crimea" ,code: "#NA"},
	// {name: "Donetsk" ,code: "#NA"},
	// {name: "Luhansk" ,code: "#NA"},
	{ name: 'Afghanistan', code: 'AF' },
	{ name: 'Albania', code: 'AL' },
	{ name: 'Barbados', code: 'BB' },
	{ name: 'Belarus', code: 'BY' },
	{ name: 'Bosnia and Herzegovina', code: 'BA' },
	{ name: 'Burkina Faso', code: 'BF' },
	{ name: 'Burma', code: 'BU' },
	{ name: 'Cambodia', code: 'KH' },
	{ name: 'Canada', code: 'CA' },
	{ name: 'Cayman Islands', code: 'KY' },
	{ name: 'Central African Republic', code: 'CF' },
	{ name: 'Congo', code: 'CG' },
	{ name: 'Cuba', code: 'CU' },
	{ name: 'Gibraltar', code: 'GI' },
	{ name: 'Haiti', code: 'HT' },
	{ name: 'Iran', code: 'IR' },
	{ name: 'Iraq', code: 'IQ' },
	{ name: 'Jamaica', code: 'JM' },
	{ name: 'Jordan', code: 'JO' },
	{ name: 'Lebanon', code: 'LB' },
	{ name: 'Libya', code: 'KY' },
	{ name: 'Mali', code: 'ML' },
	{ name: 'Malta', code: 'MT' },
	{ name: 'Montenegro', code: 'ME' },
	{ name: 'Morocco', code: 'MA' },
	{ name: 'Mozambique', code: 'MZ' },
	{ name: 'Myanmar', code: 'MM' },
	{ name: 'Nicaragua', code: 'NI' },
	{ name: 'North Korea', code: 'KP' },
	{ name: 'Pakistan', code: 'PK' },
	{ name: 'Panama', code: 'PA' },
	{ name: 'Philippines', code: 'PH' },
	{ name: 'Russia', code: 'RU' },
	{ name: 'Serbia', code: 'RS' },
	{ name: 'Senegal', code: 'SN' },
	{ name: 'South Sudan', code: 'SS' },
	{ name: 'Somalia', code: 'SO' },
	{ name: 'Syria', code: 'SY' },
	{ name: 'Türkiye', code: 'TR' },
	{ name: 'United States', code: 'US' },
	{ name: 'United Kingdom', code: 'GB' },
	{ name: 'Venezuela', code: 'VE' },
	{ name: 'Uganda', code: 'UG' },
	{ name: 'Ukrainian', code: 'UA' },
	{ name: 'United Arab Emirates', code: 'AE' },
	{ name: 'Yemen', code: 'YE' },
	{ name: 'Zimbabwe', code: 'ZW' },
];
