name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  changes:
    runs-on: ubicloud
    outputs:
      common-ts: ${{ steps.filter.outputs.common-ts }}
      posthog-types: ${{ steps.filter.outputs.posthog-types }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2
        id: filter
        with:
          filters: |
            common-ts:
              - 'common-ts/**'
              - 'bun.lock'
              - 'package.json'
            posthog-types:
              - 'posthog-types/**'
              - 'bun.lock'
              - 'package.json'

  common-ts:
    needs: changes
    if: ${{ needs.changes.outputs.common-ts == 'true' }}
    runs-on: ubicloud
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./common-ts
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24.x.x'

      - name: Setup bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: 1.2.15

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun run test:ci

  ci-passed:
    needs: [common-ts]
    if: always()
    runs-on: ubicloud
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ needs.common-ts.result }}" == "failure" ]]; then
            exit 1
          fi

  # posthog-types:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.posthog-types == 'true' }}
  #   runs-on: ubicloud
  #   timeout-minutes: 10
  #   defaults:
  #     run:
  #       working-directory: ./posthog-types
  #   steps:
  #     - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

  #     - name: Setup Node
  #       uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
  #       with:
  #         node-version: '24.x.x'

  #     - name: Setup bun
  #       uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
  #       with:
  #         bun-version: 1.2.15

  #     - name: Install dependencies
  #       run: bun install --frozen-lockfile

  #     - name: Build
  #       run: bun run build
