name: common_unit_tests

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    paths:
      - 'common-ts/**'
      - 'protocol/sdk/**'
      - '.github/workflows/common_unit_tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.x'
          cache: 'yarn'

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.15

      - name: Build SDK
        run: |
          yarn
          yarn build
        working-directory: protocol/sdk

      - name: Build Common
        run: |
          yarn
          yarn build
        working-directory: common-ts

      - name: Run Common Tests
        run: |
          yarn test:ci
        working-directory: common-ts
